name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

env:
  POWERSHELL_TELEMETRY_OPTOUT: 1

permissions:
  contents: read
  security-events: write

jobs:
  lint-and-analyze:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -Repository PSGallery
          Write-Host "PSScriptAnalyzer installed successfully"

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          if (-not (Test-Path ./src)) {
            Write-Host "Source directory ./src not found, skipping analysis"
            exit 0
          }
          
          $results = Invoke-ScriptAnalyzer -Path ./src -Recurse -Settings PSGallery
          $errors = $results | Where-Object { $_.Severity -eq 'Error' }
          $warnings = $results | Where-Object { $_.Severity -eq 'Warning' }
          
          Write-Host "PSScriptAnalyzer Results:"
          Write-Host "  Errors: $($errors.Count)"
          Write-Host "  Warnings: $($warnings.Count)"
          
          if ($errors.Count -gt 0) {
            Write-Host "❌ Errors found:" -ForegroundColor Red
            $errors | ForEach-Object {
              Write-Host "  $($_.RuleName): $($_.Message) (Line $($_.Line))" -ForegroundColor Red
            }
            exit 1
          }
          
          if ($warnings.Count -gt 0) {
            Write-Host "⚠️ Warnings found:" -ForegroundColor Yellow
            $warnings | ForEach-Object {
              Write-Host "  $($_.RuleName): $($_.Message) (Line $($_.Line))" -ForegroundColor Yellow
            }
          } else {
            Write-Host "✅ No issues found"
          }

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
          Write-Host "Pester installed: $(Get-Module Pester -ListAvailable | Select-Object -First 1 | Select-Object -ExpandProperty Version)"

      - name: Test module import
        shell: pwsh
        run: |
          try {
            Import-Module ./src/AcquisitionToolkit.psm1 -Force
            $functions = Get-Command -Module AcquisitionToolkit
            Write-Host "✅ Module imported successfully with $($functions.Count) functions"
          }
          catch {
            Write-Host "❌ Failed to import module: $($_.Exception.Message)"
            exit 1
          }

      - name: Run CI tests
        shell: pwsh
        timeout-minutes: 5
        run: |
          if (Test-Path './tests/unit/AcquisitionToolkit.CI.Tests.ps1') {
            $config = New-PesterConfiguration
            $config.Run.Path = './tests/unit/AcquisitionToolkit.CI.Tests.ps1'
            $config.Run.PassThru = $true
            $config.TestResult.Enabled = $true
            $config.TestResult.OutputPath = './test-results.xml'
            $config.TestResult.OutputFormat = 'NUnitXml'
            $config.CodeCoverage.Enabled = $false
            $config.Output.Verbosity = 'Normal'
            $config.Filter.Tag = @('Fast', 'CI')
            
            $results = Invoke-Pester -Configuration $config
            
            Write-Host "Test Results:"
            Write-Host "  Total: $($results.TotalCount)"
            Write-Host "  Passed: $($results.PassedCount)"
            Write-Host "  Failed: $($results.FailedCount)"
            Write-Host "  Skipped: $($results.SkippedCount)"
            
            if ($results.FailedCount -gt 0) {
              Write-Host "❌ Some tests failed"
              exit 1
            } else {
              Write-Host "✅ All tests passed"
            }
          } else {
            Write-Host "⚠️ CI test file not found, running basic smoke test"
            Import-Module ./src/AcquisitionToolkit.psm1 -Force
            $functions = Get-Command -Module AcquisitionToolkit
            if ($functions.Count -gt 10) {
              Write-Host "✅ Smoke test passed - $($functions.Count) functions exported"
            } else {
              Write-Host "❌ Smoke test failed - only $($functions.Count) functions exported"
              exit 1
            }
          }

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-windows
          path: test-results.xml
          retention-days: 7

  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
          Write-Host "Pester installed: $(Get-Module Pester -ListAvailable | Select-Object -First 1 | Select-Object -ExpandProperty Version)"

      - name: Test module import
        shell: pwsh
        run: |
          try {
            Import-Module ./src/AcquisitionToolkit.psm1 -Force
            $functions = Get-Command -Module AcquisitionToolkit
            Write-Host "✅ Module imported successfully with $($functions.Count) functions"
          }
          catch {
            Write-Host "❌ Failed to import module: $($_.Exception.Message)"
            exit 1
          }

      - name: Run basic tests
        shell: pwsh
        timeout-minutes: 3
        run: |
          if (Test-Path './tests/unit/AcquisitionToolkit.CI.Tests.ps1') {
            $config = New-PesterConfiguration
            $config.Run.Path = './tests/unit/AcquisitionToolkit.CI.Tests.ps1'
            $config.Run.PassThru = $true
            $config.CodeCoverage.Enabled = $false
            $config.Output.Verbosity = 'Normal'
            $config.Filter.Tag = @('Fast')
            
            $results = Invoke-Pester -Configuration $config
            
            if ($results.FailedCount -gt 0) {
              Write-Host "❌ Some tests failed on Ubuntu"
              exit 1
            } else {
              Write-Host "✅ Ubuntu tests passed"
            }
          } else {
            Write-Host "✅ Basic module test passed on Ubuntu"
          }

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

  docs-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check required documentation
        run: |
          echo "📚 Checking documentation files..."
          
          required_files=("README.md" "Phases.md")
          missing_files=()
          
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              missing_files+=("$file")
            fi
          done
          
          if [ ${#missing_files[@]} -gt 0 ]; then
            echo "❌ Missing required files:"
            printf '%s\n' "${missing_files[@]}"
            exit 1
          fi
          
          echo "✅ All required documentation files present"

      - name: Check README quality
        run: |
          echo "📖 Checking README.md quality..."
          
          if ! grep -q "# Forensic Triage Toolkit" README.md; then
            echo "❌ README.md missing main title"
            exit 1
          fi
          
          if grep -q "TODO\|FIXME\|XXX" README.md; then
            echo "⚠️ README.md contains TODO/FIXME markers"
          fi
          
          echo "✅ README.md quality check passed"

  build:
    name: Build Package
    runs-on: windows-latest
    needs: [lint-and-analyze, test-windows]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer, Pester -Force -Scope CurrentUser

      - name: Test build script
        shell: pwsh
        run: |
          if (Test-Path './build.ps1') {
            Write-Host "🔨 Running build script..."
            ./build.ps1 -Task Package -SkipTests -SkipAnalysis
          } else {
            Write-Host "⚠️ No build script found, creating basic package..."
            New-Item -Path './build-output' -ItemType Directory -Force
            $version = "1.0.0"
            Compress-Archive -Path './src', './README.md', './Phases.md' -DestinationPath "./build-output/AcquisitionToolkit-v$version.zip"
            Write-Host "✅ Package created: AcquisitionToolkit-v$version.zip"
          }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-package
          path: build-output/
          retention-days: 30 